version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=backend_flask.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8080 backend_flask:app
    restart: unless-stopped

networks:
  default:
    driver: bridge